apiVersion: v1
kind: Service
metadata:
  name: the-project
spec:
  type: NodePort
  selector:
    app: the-project # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080 # This is the port that is available outside. Value for nodePort can be between 30000-32767
      protocol: TCP
      port: 3004
      targetPort: 3001 # This is the target port